version: "3"

services:
    development:
        environment:
            - TZ=Europe/Zurich
        build:
            context: .
            dockerfile: development.Dockerfile
        ports:
            - 8080:8080
