version: "3"

services:
    wattpilot:
        environment:
            - TZ=Europe/Zurich
        build:
            context: .
            dockerfile: docker/runtime.Dockerfile
        command: python wattpilot.py --fake-devices
        ports:
            - 8080:8080
