version: "3"

services:
    wattpilot:
        command: python wattpilot.py
        ports:
            - 80:8080
        devices:
            - "/dev/gpiomem:/dev/gpiomem"
            - "/dev/mem:/dev/mem"
        restart: unless-stopped
