version: "3"

services:
    wattpilot:
        command: python wattpilot.py
        devices:
            - "/dev/gpiomem:/dev/gpiomem"
            - "/dev/mem:/dev/mem"
        restart: unless-stopped
        logging:
            driver: "journald"
